# Generated by Django 2.2.3 on 2019-08-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='gender')),
                ('mail', models.EmailField(blank=True, max_length=255, verbose_name='mail')),
                ('auth', models.PositiveIntegerField(verbose_name='auth')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff status')),
            ],
        ),
    ]
